### ISSUE TITLE
is it ready to use?

### ISSUE THREAD

**Issue by anantsparrow** [desyed/likho#3]

**Comment by desyed** [comment]
Still working. Hope within two days it will be workable @anantsparrow

**Comment by anantsparrow** [comment]
okay, will this have custom domain support for users?

**Comment by desyed** [comment]
@anantsparrow Yes, currently users can have subdomain. In next version we will give custom domain support as well.
Now Site is live and working. You are welcome to visit likho.site.

Steps to have Sub-domain
01. Sign up and create a project
02. Go to the project details page
04. Click `Generate Subdomain` Button
05. Fill the form with your desired name and hit `enter`
